project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Posts
        href: projects.qmd
      - text: Notes
        href: notes.qmd
    right:
      - text: CV
        href: resume.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    code-link: true
    code-fold: show
    code-tools: true
    highlight-style: github

editor: visual

