---
title: "Curriculum Vitae"
format:
  html:
    toc: true
    code-link: false
  pdf:
    author: Fahim Ahmed
#    pdf-engine: weasyprint
css: cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
Fahim Ahmed ||  803-904-6752  ||  fahim.ahmed.rd{at}gmail.com
:::

## WORK EXPERIENCE{style="page-break-before: always"}

### Associate System Performance Engineer

***SCDOT*** [Sep 2022 -- Present]{.cvdate}


### Instructor

***University of South Carolina*** [Aug 2019 -- Dec 2022]{.cvdate}


### Graduate Research Assistant

***University of South Carolina*** [Aug 2015 -- Dec 2022]{.cvdate}




## EDUCATION

**Ph.D. Candidate -- Civil Engineering** <br> 
*University of South Carolina* [*Present*]{.cvdate}


**Master in Applied Statistics -- ** <br> 
*University of South Carolina* [*2020*]{.cvdate}

**Master of Science -- ** <br> 
*University of South Carolina* [*2018*]{.cvdate}



::: {.no-print}
## PRESENTATIONS AND WORKSHOPS

-   Talk: [Misadventures with Reproducibility in R](https://github.com/cynthiahqy/rladies-2022-11) (30 Nov 2022, R Ladies Melbourne Meetup)
-   Talk: [Designing R Packages](https://github.com/cynthiahqy/design-r-magic_2022-10) (4 Oct 2022, Monash EBS Data Science Research Software Study Group)
-   Talk: [Quarto Websites as Research Compendiums](https://github.com/cynthiahqy/quarto-wiki-template) (16 Aug 2022, Monash EBS Data Science Research Software Study Group)
-   Workshop: [Writing academic papers with Rmarkdown and friends](https://www.cynthiahqy.com/posts/r-markdown-and-friends/) (9 Aug 2022, Monash University)
:::

::: {.print-only}
## References
Available upon request
:::